### ISSUE TITLE
Specifying specific functions from an impl

### ISSUE THREAD

**Issue by vi** [dtolnay/cargo-expand#38]
Surrectly it seems to only support modules and top-level things.

Maybe it should also support expanding only specific impl or specific function inside impl?

**Comment by dtolnay** [comment]
Seems reasonable! I would accept a PR making it work for individual impl items.

For functions inside an impl, we will need to preserve the surrounding impl's signature but we can hide other items in the impl:

```rust
// original
impl S {
    fn unrelated1(&self) {}

    fn relevant(&self) {}

    fn unrelated2(&self) {}
}

// cargo expand S::relevant
impl S {
    fn relevant(&self) {}
}
```

because rustfmt will fail to format `fn relevant(&self) {}` by itself.

**Comment by vi** [comment]
Stretch goal: nested functions, individual lines/expressions (by filename:linenum).

**Comment by dtolnay** [comment]
The current logic is very basic:

https://github.com/dtolnay/cargo-expand/blob/4101decec3d17cd90cebdb27c0093e99b2589fb5/src/filter.rs#L58-L64

(with some boilerplate for listing the contents of an item and finding the name of an item).

There are three ways to make this more intelligent:

- Change `contents_of_item` to support entering into more types of things, such as function bodies.
- Change `name_of_item` to assign names to things that don't currently have names, like maybe an impl block `impl Trait for S { fn foo }` should be accessible as S::foo.
- Change the logic so that it preserves the enclosing impl block like I wrote in my previous comment to help rustfmt.

**Comment by dtolnay** [comment]
I switched to using https://github.com/TedDriggs/syn-select in 0.4.8 for the expand-one-item behavior, which supports much more intelligent specification of items. Any remaining feature requests for the selection behavior should be filed against that repo.

**Comment by dtolnay** [comment]
FYI @TedDriggs
