### ISSUE TITLE
Add option to support theme for white terminals

### ISSUE THREAD

**Issue by TedDriggs** [dtolnay/cargo-expand#44]
See mre/prettyprint#5 - right now `cargo expand` produces unreadable output on macOS.

![screen shot 2019-01-24 at 8 32 08 am](https://user-images.githubusercontent.com/4805575/51710822-2591f000-1fdf-11e9-98f4-fac878058448.png)

There's a workaround to use unhighlighted output, but having the best of both worlds would be great.

**Comment by dtolnay** [comment]
Implemented in 0.4.9. https://github.com/dtolnay/cargo-expand#configuration

**Comment by kornelski** [comment]
I've ran into the same problem. My terminal background is gray, so it turns out to be hard to read with both dark and light themes :(

<img width="685" alt="Screenshot 2019-03-17 at 23 04 20" src="https://user-images.githubusercontent.com/72159/54499392-25401200-4909-11e9-9a70-ecbcdf89a1ec.png">

I suggest either forcing a background color of all text to match theme's background color, or not using themes by default.
